推しの素晴らしい写真を人数分リストで並べる
jphacks/tk_2420 pull request #95
Opened 2024-11-13 15:09 UTC by watanabe-seiya441

4人いたら4行のリストができる

2024-11-13 15:32 UTC, hara82 requested changes

2024-11-13 15:32 UTC, hara82 commented on TS/oshinoko/app/ui/ListOshiImages.tsx
> +    const fetchMembers = async () => {
メンバーの名前情報がほしいだけなら、　api/annotation_labels/ にGETを投げれば返ってくるからこっちのほうが自然かな。
annotation_labelsという名前がよろしくないのはそうなんだけど

2024-11-13 15:32 UTC, hara82 commented on TS/oshinoko/app/ui/ListOshiImages.tsx
> +        const response = await fetch(overlayConfigUrl);
下はaxiosで、ここはfetch なのは違和感がある。

2024-11-14 05:38 UTC, watanabe-seiya441 commented on TS/oshinoko/app/ui/ListOshiImages.tsx
> +        const response = await fetch(overlayConfigUrl);
axiosに統一します。

2024-11-14 09:32 UTC, hara82 commented
これは、曲と人ごとにディレクトリを作りまくる？
曲が増えたり、大人数のグループだと現実的でなくない？

2024-11-14 10:10 UTC, hara82 approved these changes
写真のディレクトリを作りまくるのは回避したいけど、とりあえずマージしてもよいかなと思います。

2024-11-14 10:15 UTC, watanabe-seiya441 commented
> 写真のディレクトリを作りまくるのは回避したいけど、とりあえずマージしてもよいかなと思います。

ディレクトリ構造を変更する案が思いつきません。
ビデオアップロード数に上限を定めたり古い部分を削除したりすれば良いのかな?

2024-11-14 10:15 UTC, watanabe-seiya441 commented
マージします

2024-11-14 10:16 UTC, merged